#!/bin/bash

## bootstrap - Entry point of AWS Lambda Julia runtime
## 2018 (C) Fugro ROAMES <marines@roames.com.au>


set -euo pipefail

CLIENT_MODULE=$(echo $_HANDLER | cut -d. -f1)

${LAMBDA_TASK_ROOT}/bin/julia -i -e \
	"using AWSLambdaJuliaRuntime; " \
	"using mod_${_HANDLER}; " \
	"AWSLambdaJuliaRuntime.main(${CLIENT_MODULE});"

