#!/bin/bash

## bootstrap - Entry point of AWS Lambda Julia runtime
## 2018 (C) Fugro ROAMES <marines@roames.com.au>


set -euo pipefail

CLIENT_MODULE=$(echo $_HANDLER | cut -d. -f1)

# DEBUG - REMOVE LATER
echo "AWS Lambda Julia Runtime"
env
echo "========================"
pwd

ls -la ${LAMBDA_TASK_ROOT}
ls -la ${LAMBDA_TASK_ROOT}/bin/
echo "================================="
######################

${LAMBDA_TASK_ROOT}/bin/julia -i -e \
	"using AWSLambdaJuliaRuntime; " \
	"using ${CLIENT_MODULE}; " \
	"AWSLambdaJuliaRuntime.main(${CLIENT_MODULE});"

